import { Map } from "@type/map";

export const maps: Map[] = [
  {
    id: 0,
    title: "Aztec world",
    colors: {
      backgroundColor: "#E3B499",
      percentShadowColor: "#402919",
      percentBackgroundColor: "#754A2C",
      titleColor: "#fff",
      titleShadowColor: "#754A2C",
    },
    levels: [
      { id: 1, positionX: 169, positionY: 1200, reward: null },
      { id: 2, positionX: 225, positionY: 1149, reward: null },
      {
        id: 3,
        positionX: 310,
        positionY: 1141,
        reward: { placement: "top", type: "diamond", count: 2 },
      },
      { id: 4, positionX: 219, positionY: 1053, reward: null },
      { id: 5, positionX: 127, positionY: 1097, reward: null },
      {
        id: 6,
        positionX: 23,
        positionY: 1106,
        reward: { placement: "top", type: "diamond", count: 2 },
      },
      { id: 7, positionX: 61, positionY: 968, reward: null },
      { id: 8, positionX: 164, positionY: 982, reward: null },
      {
        id: 9,
        positionX: 298,
        positionY: 1004,
        reward: { placement: "top", type: "diamond", count: 2 },
      },
      { id: 10, positionX: 236, positionY: 881, reward: null },
      { id: 11, positionX: 134, positionY: 903, reward: null },
      {
        id: 12,
        positionX: 21,
        positionY: 906,
        reward: { placement: "top", type: "fragment", count: 2 },
      },
      { id: 13, positionX: 104, positionY: 799, reward: null },
      { id: 14, positionX: 182, positionY: 830, reward: null },
      {
        id: 15,
        positionX: 297,
        positionY: 830,
        reward: { placement: "top", type: "diamond", count: 2 },
      },
      { id: 16, positionX: 233, positionY: 717, reward: null },
      { id: 17, positionX: 164, positionY: 749, reward: null },
      {
        id: 18,
        positionX: 29,
        positionY: 745,
        reward: { placement: "top", type: "coin", count: 2 },
      },
      { id: 19, positionX: 94, positionY: 673, reward: null },
      {
        id: 20,
        positionX: 169,
        positionY: 633,
        reward: { placement: "right", type: "diamond", count: 2 },
      },
      { id: 21, positionX: 225, positionY: 582, reward: null },
      {
        id: 22,
        positionX: 310,
        positionY: 574,
        reward: { placement: "top", type: "diamond", count: 2 },
      },
      { id: 23, positionX: 219, positionY: 486, reward: null },
      { id: 24, positionX: 127, positionY: 530, reward: null },
      {
        id: 25,
        positionX: 23,
        positionY: 539,
        reward: { placement: "top", type: "diamond", count: 2 },
      },
      { id: 26, positionX: 61, positionY: 401, reward: null },
      { id: 27, positionX: 164, positionY: 415, reward: null },
      {
        id: 28,
        positionX: 298,
        positionY: 437,
        reward: { placement: "top", type: "diamond", count: 2 },
      },
      { id: 29, positionX: 236, positionY: 314, reward: null },
      { id: 30, positionX: 134, positionY: 336, reward: null },
      {
        id: 31,
        positionX: 21,
        positionY: 339,
        reward: { placement: "top", type: "diamond", count: 2 },
      },
      { id: 32, positionX: 104, positionY: 232, reward: null },
      { id: 33, positionX: 182, positionY: 263, reward: null },
      {
        id: 34,
        positionX: 297,
        positionY: 263,
        reward: { placement: "top", type: "diamond", count: 2 },
      },
      { id: 35, positionX: 233, positionY: 150, reward: null },
      { id: 36, positionX: 161, positionY: 182, reward: null },
      {
        id: 37,
        positionX: 20,
        positionY: 160,
        reward: { placement: "top", type: "diamond", count: 2 },
      },
      {
        id: 38,
        positionX: 94,
        positionY: 106,
        reward: null,
      },
      {
        id: 39,
        positionX: 186,
        positionY: 49,
        reward: null,
      },
      { id: 40, positionX: 236, positionY: 3, reward: null },
    ],
  },
];
