stages:
  - build
  - deploy

# CF:
#   stage: build
#   image: node:20.13.1
#   script:
#     - npm install
#     - npm run build
#     - npm install -g wrangler --unsafe-perm=true
#     - wrangler pages publish ./dist --project-name=app-empiresbattle-com --branch=main
#   rules:
#     - if: '$CI_COMMIT_BRANCH == "main"'

# default:
#  image: docker:24.0.7
#  services:
#    - docker:24.0.7-dind

build:
 stage: build
 before_script:
   - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
 script:
   - docker build -t ${CI_REGISTRY_IMAGE}/app:${CI_COMMIT_SHORT_SHA} .
   - docker push ${CI_REGISTRY_IMAGE}/app:${CI_COMMIT_SHORT_SHA}

prod:
 stage: deploy
 before_script:
   - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
 script:
   - docker compose up -d
 rules:
   - if: '$CI_COMMIT_BRANCH == "main"'
 tags:
   - prod-app

dev:
 stage: deploy
 before_script:
   - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
 script:
   - docker-compose -f docker-compose.dev.yml up -d
 rules:
   - if: '$CI_COMMIT_BRANCH == "dev"'
 tags:
   - dev
